version: "3.9"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    networks:
      - caddy
    environment:
      BACKEND_URL: $BACKEND_URL
      BASE_IMAGE_URL: $BASE_IMAGE_URL

networks:
  caddy:
    external: true
