version: "3.9"

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      PGHOST: $PGHOST
      PGUSER: $PGUSER
      PGDATABASE: $PGDATABASE
      PGPASSWORD: $PGPASSWORD
      AUTHSECRET: $AUTHSECRET
      S3_URL: $S3_URL
      S3_ACCESS_KEY: $S3_ACCESS_KEY
      S3_SECRET_KEY: $S3_SECRET_KEY
      S3_BUCKET: $S3_BUCKET
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: $PGDATABASE
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD
    volumes:
      - ./.tmp/volumes/db/data:/var/lib/postgresql/data