version: "3.9"

services:
  api:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: $PGDATABASE
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD
    ports:
      - "5432:5432"
  caddy:
    container_name: caddy
    image: caddy:2.7.6
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
